In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. Програма, що генерує випадкові масиви різними способами, зазначеними в теоретичних відомостях.
array_1 = np.random.random((3,3))
array_2 = np.random.randint(1,10,(3,3))

display(array_1, array_2)

array([[0.19147528, 0.91552637, 0.92881691],
       [0.11827455, 0.43498785, 0.1035586 ],
       [0.41662599, 0.65607658, 0.15370474]])

array([[1, 9, 5],
       [9, 3, 9],
       [1, 8, 6]])

In [3]:
# 2. Програма, що демонструє звернення до елементів масиву за допомогою індексів, 
# в тому числі від’ємних; виділення підмасивів.

subarray = array_2[0:2,0:2]
display(array_2[0,0], array_2[-1,-1], array_2[1], subarray)

1

6

array([9, 3, 9])

array([[1, 9],
       [9, 3]])

In [4]:
# 3. Программа, що демонструє основні арифметичні операції над масивами, а також роботу
# методів reduce, accumulate, outer.

display(array_2+1, array_2-2, array_2*2, array_2/2, array_2**2, array_2%2, -array_2)
display(np.add.reduce(array_2), np.subtract.accumulate(array_2), np.divide.outer(array_2,array_2))

array([[ 2, 10,  6],
       [10,  4, 10],
       [ 2,  9,  7]])

array([[-1,  7,  3],
       [ 7,  1,  7],
       [-1,  6,  4]])

array([[ 2, 18, 10],
       [18,  6, 18],
       [ 2, 16, 12]])

array([[0.5, 4.5, 2.5],
       [4.5, 1.5, 4.5],
       [0.5, 4. , 3. ]])

array([[ 1, 81, 25],
       [81,  9, 81],
       [ 1, 64, 36]], dtype=int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]], dtype=int32)

array([[-1, -9, -5],
       [-9, -3, -9],
       [-1, -8, -6]])

array([11, 20, 20])

array([[  1,   9,   5],
       [ -8,   6,  -4],
       [ -9,  -2, -10]], dtype=int32)

array([[[[1.        , 0.11111111, 0.2       ],
         [0.11111111, 0.33333333, 0.11111111],
         [1.        , 0.125     , 0.16666667]],

        [[9.        , 1.        , 1.8       ],
         [1.        , 3.        , 1.        ],
         [9.        , 1.125     , 1.5       ]],

        [[5.        , 0.55555556, 1.        ],
         [0.55555556, 1.66666667, 0.55555556],
         [5.        , 0.625     , 0.83333333]]],


       [[[9.        , 1.        , 1.8       ],
         [1.        , 3.        , 1.        ],
         [9.        , 1.125     , 1.5       ]],

        [[3.        , 0.33333333, 0.6       ],
         [0.33333333, 1.        , 0.33333333],
         [3.        , 0.375     , 0.5       ]],

        [[9.        , 1.        , 1.8       ],
         [1.        , 3.        , 1.        ],
         [9.        , 1.125     , 1.5       ]]],


       [[[1.        , 0.11111111, 0.2       ],
         [0.11111111, 0.33333333, 0.11111111],
         [1.        , 0.125     , 0.16666667

In [2]:
# 4. Програма, що вираховує статистичні характеристики, а саме, мінімальне і
# максимальне значення, вибіркові середнє, дисперсію,
# середньоквадратичне відхилення, медіану та 25 та 75 персентилі,
# величини ширина пелюстки (petal_width) з набору даних щодо квіток
# ірису (iris.csv).

data = pd.read_csv('iris.csv')['petal_width']

display(np.min(data), np.max(data), np.mean(data))
display(np.var(data), np.std(data), np.median(data), np.percentile(data, 25), np.percentile(data, 75))

0.1

2.5

1.1986666666666668

0.5785315555555555

0.7606126185881716

1.3

0.3

1.8

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=41d21095-808e-4654-a83b-3b85aff35b7d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>